services:
  # Service untuk aplikasi Streamlit
  dashboard:
    container_name: lpse-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: latest
    ports:
      - "7000:8501"
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./data:/app/data
    env_file:
      - .env
      
  # Service untuk crawler
  crawler:
    container_name: lpse-crawler
    build:
      context: .
      dockerfile: Dockerfile.crawler
      args:
        TAG: latest
    restart: always
    volumes:
      - ./data:/app/data
    command: ["cron", "-f"]
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    depends_on:
      - dashboard
